services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=yadwy_db'
      - 'POSTGRES_PASSWORD=yadwy_pass'
      - 'POSTGRES_USER=yadwy_user'
    ports:
      - '5434:5432'
