services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=yadwy_db'
      - 'POSTGRES_PASSWORD=yadwy_pass'
      - 'POSTGRES_USER=yadwy_user'
    ports:
      - '5434:5432'
